### PR TITLE
 aur-sync: Allow reading package names from standard input 

### PR DESCRIPTION
**Pull request by CyberShadow**
For when you want the latest commit of *everything*.

### CODE REVIEW

**Comment by maximbaz** [comment]
Maybe you are looking for #283?

**Comment by AladW** [comment]
Since `pkgname` cannot contain spaces or tabs, you could use `aur-sync --list`
```
aur sync $(aur sync --list | jq .pkgname)
```
I guess you could add something like this to take packages from stdin (newline separated, as `pacman`)
```
for arg in "$@"; do
  case $arg in
    -) stdin=1 ;;
  esac
done

if ((stdin)); then
  mapfile -t pkg_stdin
  set -- "$@" "${pkg_stdin[@]}"
fi
```
so the above transforms to:
```
aur sync --repo-list | jq .name | aur sync -
```

**Comment by CyberShadow** [comment]
Ahh, thanks! It did seem too easy.

> That said, you can already achieve the above with command substitution

That works! Though I think you meant ` | jq -r '.[][].pkgname'`.

> I guess you could add something like this to take packages from stdin

OK, I turned this PR into a change that implements it. How's this?

**Comment by AladW** [comment]
Nice, I like the `cat` trick. :+1:

**Comment by AladW** [comment]
Hmm, I wonder what happens if you specify `-` twice?

**Comment by CyberShadow** [comment]
The second cat hits EOF immediately, so it's a no-op.

```shell
$ echo test | ( cat ; cat )
test
```

**Comment by AladW** [comment]
All right, thanks for clarifying.

**Comment by AladW** [comment]
Not sure it works completely as intended: https://github.com/jrudess/aurutils-plugins/blob/master/lib/aur-update-devel#L20-L23

**Comment by Earnestly** [comment]
@AladW fwiw, you can `declare -l` the `reponse` variable to avoid needing to do any case matching.

```
help declare
...
      -l	to convert NAMEs to lower case on assignment
```

**Comment by CyberShadow** [comment]
One possibility is that aurutils could read interactive responses from the TTY directly, like `sudo`. That would however mean that `yes` and similar programs become unusable (at least not without being combined with `script` or such).

**Comment by Earnestly** [comment]
Indeed, please don't ever do that.

**Comment by AladW** [comment]
I guess a better approach is to instead add `-a` to aur-sync. Then you could do
```
aur sync --no-ver-shallow -a <(cut -d: -f1 updates)
```
Not sure if there's still much benefit in `-` then, though programs like `xargs` support both `-a` and `-`.

**Pull request merged**
