### PR TITLE
aursync: fix order of arguments passed to aurcheck

### PR DESCRIPTION
**Pull request by djmattyg007**

### CODE REVIEW

**Comment by djmattyg007** [comment]
I found that when passed after the non-option arguments, the `-r` argument was ignored by `getopts`.

**Comment by AladW** [comment]
Perhaps it's better to use an explicit argument for the database in `aurcheck`, similar to `aurbuild -d`, instead of relying on an exact order?

**Comment by djmattyg007** [comment]
I'm comfortable with that.

**Comment by AladW** [comment]
Thanks!

**Pull request closed without merging**
