### PR TITLE
Update and sync aur.1

### LINKED ISSUE #480: `man aur` should reference `aur-repo`

### PR DESCRIPTION
**Pull request by alfunx**
* Mention `aur-repo` and `aur-vercmp-devel`
* Use imperative
* Use description provided in sub-man-pages
* Use Aurweb instead of AurJson

Fixes #480

### CODE REVIEW

**Comment by AladW** [comment]
Should aurweb be capitalized or not? https://aur.archlinux.org/rpc.php
>the aurweb RPC Interface

**Comment by alfunx** [comment]
Oh I was looking [at the Arch Wiki](https://wiki.archlinux.org/index.php/Aurweb_RPC_interface). I guess aur.archlinux.org/rpc.php is more official, should I lowercase it?

**Comment by AladW** [comment]
Yeah, we should use lower case if upstream does.

**Comment by AladW** [comment]
:+1:

**Pull request merged**
