### PR TITLE
query: build JSON manually for union as well

### PR DESCRIPTION
**Pull request by AladW**
https://github.com/AladW/aurutils/pull/919#issuecomment-1037148568

### CODE REVIEW

**Comment by CyberShadow** [comment]
If you just want to pick the first objects in an array with a field having some value, you could try e.g. `group_by(.ID) | map(.[0])`.

Otherwise a self-contained example of the problem would help :)

**Comment by AladW** [comment]
A self-contained example is as follows:
```bash
aur query -t search bacula-dir-mariadb ros-melodic-mbf-costmap-nav kaption helium-ledger-cli python-jamo-git qdc kwin-scripts-sticky-window-snapping-git maestral-qt exec-helper-docs deepin-wine-plugin | jq -s add
```
returns
```json
{
  "resultcount": 2,
  "results": [
    {
      "Description": "Deepin Wine plugin virtual package",
      "FirstSubmitted": 1524900490,
      "ID": 814453,
      "LastModified": 1604648028,
      "Maintainer": "Skywol",
      "Name": "deepin-wine-plugin-virtual",
      "NumVotes": 4,
      "OutOfDate": null,
      "PackageBase": "deepin-wine-plugin-virtual",
      "PackageBaseID": 131921,
      "Popularity": 0.598254,
      "URL": "http://www.deepin.org",
      "URLPath": "/cgit/aur.git/snapshot/deepin-wine-plugin-virtual.tar.gz",
      "Version": "5.1.13-1"
    },
    {
      "Description": "Deepin Wine plugin",
      "FirstSubmitted": 1524899634,
      "ID": 814455,
      "LastModified": 1604648148,
      "Maintainer": "Skywol",
      "Name": "deepin-wine-plugin",
      "NumVotes": 4,
      "OutOfDate": null,
      "PackageBase": "deepin-wine-plugin",
      "PackageBaseID": 131920,
      "Popularity": 0.598254,
      "URL": "http://www.deepin.org",
      "URLPath": "/cgit/aur.git/snapshot/deepin-wine-plugin.tar.gz",
      "Version": "5.1.13-1"
    }
  ],
  "type": "search",
  "version": 5
}
```
intended result:
```
aur query -t search bacula-dir-mariadb ros-melodic-mbf-costmap-nav kaption helium-ledger-cli python-jamo-git qdc kwin-scripts-sticky-window-snapping-git maestral-qt exec-helper-docs deepin-wine-plugin  | jq -Mjcs '.[0].type as $t | .[0].version as $v
            | map(.results) | unique | add as $r
            | {
                "resultcount": ($r | length),
                "results": $r,
                "type": $t,
                "version": $v
            }' 
```
```json
{
  "resultcount": 13,
  "results": [
    {
      "Description": "A KDE utility similar to Jing or Skitch to take and edit screenshots",
      "FirstSubmitted": 1310242886,
      "ID": 514844,
      "LastModified": 1527674635,
      "Maintainer": "Hoek",
      "Name": "kaption",
      "NumVotes": 6,
      "OutOfDate": null,
      "PackageBase": "kaption",
      "PackageBaseID": 50592,
      "Popularity": 0,
      "URL": "https://www.linux-apps.com/p/1126919/",
      "URLPath": "/cgit/aur.git/snapshot/kaption.tar.gz",
      "Version": "0.1.1-3"
    },
    {
      "Description": "A Qt interface for the Maestral daemon",
      "FirstSubmitted": 1586302549,
      "ID": 910325,
      "LastModified": 1621624047,
      "Maintainer": "lmartinez-mirror",
      "Name": "maestral-qt-git",
      "NumVotes": 0,
      "OutOfDate": null,
      "PackageBase": "maestral-qt-git",
      "PackageBaseID": 151228,
      "Popularity": 0,
      "URL": "https://github.com/SamSchott/maestral-qt",
      "URLPath": "/cgit/aur.git/snapshot/maestral-qt-git.tar.gz",
      "Version": "1.4.4-1"
    },
    ...
  ],
  "type": "search",
  "version": 5
}
```

**Comment by CyberShadow** [comment]
> edit: also errors should be preserved, see #922

If you would like to preserve `.type=="error"` objects, then the output cannot be a single object.

WIP without error handling (assumes all objects are `.type=="search"`): `jq -s '([.[].results] | add) as $r | (.[0] + { "resultcount": ($r | length), "results": $r })'`

**Comment by AladW** [comment]
> If you would like to preserve .type=="error" objects, then the output cannot be a single object.

I guess this is especially noticeable when having `.type="error"` objects exclusively:
```bash
aur query -t search python | jq -s '[([.[] | select(.type == "search").results] | add) as $r | (.[0] + { "resultcount": ($r | length), "results": $r })] + [.[] | select(.type != "search")] | .[]'
```
```json
{
  "error": "Too many package results.",
  "resultcount": 0,
  "results": null,
  "type": "error",
  "version": 5
}
{
  "error": "Too many package results.",
  "resultcount": 0,
  "results": [],
  "type": "error",
  "version": 5
}
```

**Pull request merged**
