### PR TITLE
Make usage outputs more uniform

### PR DESCRIPTION
**Pull request by alfunx**
Some more documentation stuff:

* sort flags
* use `<repo>` and `<path>` more consistently
* remove `-h` / `--help` flags
* remove unused flags

### CODE REVIEW

**Comment by Earnestly** [comment]
Most `-h` flags could be avoided by simply having manuals.  A useful diagnostic message and simple usage synopsis is all a program need print if used incorrectly.

**Comment by rafasc** [comment]
To be honest, I think we can probably drop `-h|--help` flags. They creeped in with the move to `parseopts.sh` because at the time the plan was to make shell completions by parsing the help messages. That's no longer the case.

**Comment by AladW** [comment]
I would accept commits removing the `-h` flags.

**Comment by alfunx** [comment]
Done!

**Comment by AladW** [comment]
It's fine, thank you.

**Pull request merged**
