### PR TITLE
Add manjaro chroot marker file

### PR DESCRIPTION
**Pull request by bartoszek**
On manjaro `mkarchroot` creates different root marker file.
Arch=.arch-chroot, Manjaro=.manjaro-chroot

### CODE REVIEW

**Comment by rafasc** [comment]
While this looks like a very simple change, `aurutils` is written for the [Arch User Repository](https://wiki.archlinux.org/index.php/Arch_User_Repository) and depends on the Arch Linux version of dependencies, in this case: `devtools`. Keeping track of what Arch based distros are doing with their own fork of Arch packages is hard to maintain, as mentioned in the [Arch Linux Code of Conduct](https://wiki.archlinux.org/index.php/Code_of_conduct#Arch_Linux_distribution_support_*only*).

I'd say this is a ![wontfix][wontfix], but @AladW has obviously the final say.

[wontfix]:https://img.shields.io/badge/-wontfix-a8a8a8.svg

**Comment by Foxboron** [comment]
I think the comment from Dave is applicable here as well; https://github.com/archlinux/devtools/pull/9

**Comment by Earnestly** [comment]
Yes, this is the wrong place to fix it.  `mkarchroot` is unnecessarily not general purpose, so anything to work around this issue will just require more and more code instead of less.

**Comment by bartoszek** [comment]
Perhaps we could have this resolved in `prepare` function directly in `PKGBUILD` on aur ?

**Comment by bartoszek** [comment]
Now i see it, thanks for clarifying :blush:

**Pull request closed without merging**
