### PR TITLE
sync: make confirmation prompt actually allow for any key to be pressed to continue

### PR DESCRIPTION
**Pull request by terencode**
Credits to https://unix.stackexchange.com/a/293941

### CODE REVIEW

**Comment by rafasc** [comment]
I'll vote against this as it is. I Feel this makes it way too easy to agree by accident. 

Important operations that ask for user confirmation usually ask for a explicit enter.  
cf. `touch temp; rm -vi temp;` I also see no value in hiding the answer.

We could accept any answer that starts with `y` and `exit` otherwise:
```sh
read -p 'Do you want continue? [y/N] '
[[ ! $REPLY =~ ^[Yy] ]] && exit 1
```

**Comment by Earnestly** [comment]
No prompt system should respond to anything other than `Return`.

**Comment by terencode** [comment]
@Earneslty @rafasc sure but that's not one the message says. This PR only makes it match the original prompt message.

**Comment by rafasc** [comment]
@terencode Maybe the message is the thing that needs changing. 😏
I already suggested changing it to a more traditional `[y/N]` prompt. Feel free to re-spin this PR into one that does that.

**Pull request closed without merging**
