### PR TITLE
Update chroot once

### PR DESCRIPTION
**Pull request by vorph1**
Update the root chroot once before build so that the user chroot doesn't have to update base packages on each subsequent package build

### CODE REVIEW

**Comment by AladW** [comment]
This was proposed in #109. The issue is that you need to update the chroot to make it aware of new packages in the local repository. You could update it once, then use a temporary config as in `build_local()`, but I'm unsure if this is worth it.

**Comment by vorph1** [comment]
This does not remove the update that is run by makechrootpkg before each package is built, newly built packages in repo do get picked up correctly.

**Comment by AladW** [comment]
Oh, you mean that `makechrootpkg -c` restores the user copy back to the original in `$CHROOT/root`, which wasn't updated priorly. Please add a comment reflecting this as it isn't obvious from the code.

**Comment by AladW** [comment]
Thanks, merged: :+1:

**Pull request merged**
