### PR TITLE
aur: allow execution of user defined scripts

### PR DESCRIPTION
**Pull request by rafasc**
Provide a similar mechanism that `git` has for user defined sub-commands.
`git` allows the use of any executable in `$PATH` with prefix `'git-'` to be used with the main `git` command.
E.g. `'git-name'` can be invoked with `$git name`.

In aa59551, I used executables on `$PATH` that were prefixed by `'aur-'`. But in retrospect that was probably a poor choice since [there are already some packages](https://aur.archlinux.org/packages/?K=aur-) which use executables with the `'aur-'` prefix that would end up there.
One alternative is to use another prefix, something like `'aurutils-'`.

Another would be having a dedicated directory for sub-commands scripts. E.g.
```bash
USER_CMDS_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/aurutils/usrcommands
```
Besides giving the user free choice over the naming convention, not having unexpected results due to similar executables by other packages, this would also make listing available scripts (for use in completions or help messages) easier.

I think the second option is preferable, but i'll wait some feedback before pushing another commit.

### CODE REVIEW

**Comment by AladW** [comment]
Well, from a purely selfish perspective the current commit would be useful, since there's now `/bin/aur-query` and `/bin/aur-sync`. I can see your points for using a different approach though.

**Comment by maximbaz** [comment]
By the way, why do `/bin/aur-query` and `/bin/aur-sync` exist instead of `/lib/query` and `/lib/sync`?

**Comment by rafasc** [comment]
Personally, I think we shouldn't do both but it's not technically impossible... The builtin `compgen -c 'aur-'` could be used for grabbing commands from the `$PATH` that match on cases listing is needed (e.g. `aur` called without arguments).

But in the end, I assume users would probably just create something like  `.config/aurutils/scripts` to house their scripts, which is a point in favor of the second approach.

'Config directory' version could look something like [this](https://github.com/rafasc/aurutils/blob/custom-scripts-support-xdg-config/bin/aur). Which I'll merge into this if we decide it's a better way to go forward.

Also interested in the motivation behind what @maximbaz mentioned.

**Comment by AladW** [comment]
I've kept thinking about this but couldn't come up with a good reason to implement such PATH extensions. Essentially, it reminds me of the proposed support for hooks. (see #184)

So that goes back to the `aur-` prefix. The same scenario applies to `git-` - any users can upload their own programs to e.g AUR and have them be called by `git` (and in fact, many do). These programs would continue working as if they were called on their own.

To avoid confusion, `git` has a nice mechanism in the form of `git help -a`:
```
available git commands in '/usr/lib/git-core'
...
git commands available from elsewhere on your $PATH
...
```
As to `aur-sync`, I see it as something that wraps the commands, much in the vein of `aur`, rather than provide some core functionality of its own. Hence `/bin`. The same cannot be said of `aur-query`, though, so I'll think on whether to have `/lib` scripts call `/bin/aur` or simply use a fixed path.

**Comment by AladW** [comment]
In mind with the above remark on `git help -a`, I've moved all scripts back to `/lib` to allow for easy separation from third-party programs in `/bin`.

**Comment by rafasc** [comment]
In the future, if core `aur-` scripts are added to `/bin`, it should be enough to manually add them to `cmd` array.

**Comment by AladW** [comment]
I'll merge this and merge the branch to master at some point. Thanks

**Comment by rafasc** [comment]
Thank you!

**Pull request merged**
