### PR TITLE
Use OSC8 terminal hyperlinks in aur search

### PR DESCRIPTION
**Pull request by dhouck**
Many terminals use OSC 8 to allow hyperlinking text in the terminal, as
described in [here](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda "OSC8 spec"), and most that don't will silently eat the link and
just display the same text.  This adds support so that an `aur search`
can link to the AUR webpage for further information.

Note that I rarely write Bash scripts, doing most of my programming in other languages; Iʼm sure that despite what Shellcheck says Iʼve done somethnig thatʼs bad style or worse, and Iʼd be willing to fix that if pointed out.

### CODE REVIEW

**Comment by AladW** [comment]
I don't use a terminal that supports OSC8, but I guess the proposed functionality is useful if you do. I will wait a while to see if more people are interested in this feature.

**Comment by djmattyg007** [comment]
> I will wait a while to see if more people are interested in this feature.

This feature looks beneficial to me :+1:

**Comment by AladW** [comment]
I've tried this in `gnome-terminal` and it looks pretty nice. 

@Earnestly you mentioned a review, but I still can't see it in this window. Could you maybe mention it again?

**Comment by Earnestly** [comment]
I have no idea how to use this interface

**Comment by AladW** [comment]
They keep changing it, and every time it's more confusing...

**Pull request merged**
